---
- name: (CentOS/RHEL 8) Setup Python 3
  block:
    - name: (CentOS/RHEL 8) Install Python 3
      yum:
        name:
          - python3
          - python3-pip
          - python3-devel
        update_cache: true

    - name: (Centos/RHEL 8) Set Python 3 as default
      alternatives:
        name: python
        path: /usr/bin/python3
        link: /usr/bin/python
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] is version('8', '==')

- name: (Centos/RHEL) Install build tools
  yum:
    name:
      - "@Development tools"
      - ca-certificates
      - gcc
      - gd
      - gd-devel
      - glibc
      - glibc-common
      - perl-core
      - wget
      - zlib-devel
    update_cache: true
  when: ansible_facts['os_family'] == "RedHat"


- name: (Debian) Install backports repo for 'buster'
  apt_repository:
    filename: buster-backports
    repo: deb http://ftp.us.debian.org/debian buster-backports main
    update_cache: true
    mode: 0644
  when: ansible_facts['distribution_release'] == "buster"

- name: (Debian/Ubuntu) Install build tools
  apt:
    name:
      - build-essential
      - checkinstall
      - libtemplate-perl
      - python3-minimal
      - perl
      - tar
      - zlib1g-dev
      - unzip
      - uuid-dev
    update_cache: true
  when: ansible_facts['os_family'] == "Debian"

- name: Install PCRE from source
  import_tasks: pcre-install.yml

- name: Install OpenSSL from source
  import_tasks: openssl-install.yml

- name: Install ZLib from source
  import_tasks: zlib-install.yml

- name: Install pagespeed
  import_tasks: pagespeed-install.yml

- name: Install nginx
  import_tasks: nginx-install.yml
